use_frameworks!

platform :ios, '10.0'

target 'YukiExtensions_Example' do
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'YukiExtensions', :path => '../'
  pod 'CaamDauValue'
  source 'https://github.com/HFYuki/YukiSpecs'
  pod 'YukiCompatible'
  target 'YukiExtensions_Tests' do
    inherit! :search_paths

    
  end
end
